# Generated by Django 4.0.6 on 2022-07-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmovielistapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='day_complete',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='year_of_issue',
            field=models.DateField(auto_now=True),
        ),
    ]
