# Generated by Django 4.0.6 on 2022-07-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmovielistapp', '0002_alter_listitem_day_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='day_complete',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='year_of_issue',
            field=models.DateField(),
        ),
    ]
