# Generated by Django 4.0.6 on 2022-07-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmovielistapp', '0002_alter_bookmovielist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='year_of_issue',
            field=models.DateField(blank=True, max_length=4, null=True),
        ),
    ]
